name: Get Refresh Token

on:
  workflow_dispatch:

jobs:
  get-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Prepare Google credentials
      run: |
        echo '{
          "installed": {
            "client_id": "'"${{ secrets.GOOGLE_CLIENT_ID }}"'",
            "client_secret": "'"${{ secrets.GOOGLE_CLIENT_SECRET }}"'",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "redirect_uris": ["urn:ietf:wg:oauth:2.0:oob", "http://localhost"]
          }
        }' > googleAPI.json
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-auth google-auth-oauthlib google-auth-httplib2

    - name: Run get_refresh_token.py
      run: |
        python get_refresh_token.py
