name: Automated YouTube Channel

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare Google credentials
      run: |
        echo '{
          "installed": {
            "client_id": "'"${{ secrets.GOOGLE_CLIENT_ID }}"'",
            "client_secret": "'"${{ secrets.GOOGLE_CLIENT_SECRET }}"'",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "redirect_uris": ["urn:ietf:wg:oauth:2.0:oob", "http://localhost:8080"]
          }
        }' > googleAPI.json

    - name: Prepare Token credentials
      run: |
        echo '{
          "client_id": "'"${{ secrets.GOOGLE_CLIENT_ID }}"'",
          "client_secret": "'"${{ secrets.GOOGLE_CLIENT_SECRET }}"'",
          "refresh_token": "'"${{ secrets.GOOGLE_REFRESH_TOKEN }}"'",
          "token_uri": "https://oauth2.googleapis.com/token"
        }' > token.json

    - name: Run the YouTube automation script
      env:
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        python main.py
